development:
  adapter: async

test:
  adapter: async
  # adapter: test

production:
  adapter: redis
  url: redis://redistogo:d0c3650f2beb72a8e32b6897d1dffe0a@tarpon.redistogo.com:10567/
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: sezzle_backend_production
